const countLayers = require('./code');

describe('Tests', () => {
    test('the tests', () => {
        expect(countLayers(['AAA'])).toEqual(1);
        expect(countLayers(['AAAA', 'AAAA', 'AAAA'])).toEqual(1);
        expect(countLayers(['AAAA', 'ABBA', 'AAAA'])).toEqual(2);
        expect(countLayers(['AAAAAAAAA', 'ABBBBBBBA', 'ABBBBBBBA', 'ABBBBBBBA', 'AAAAAAAAA'])).toEqual(2);
        expect(countLayers(['AAAAAAAAA', 'ABBBBBBBA', 'ABBAAABBA', 'ABBBBBBBA', 'AAAAAAAAA'])).toEqual(3);
        expect(countLayers(['AAAAAAAAA', 'ABBBBBBBA', 'ABCCCCCBA', 'ABBBBBBBA', 'AAAAAAAAA'])).toEqual(3);
        expect(countLayers(['AAAAAAAAAAA', 'AABBBBBBBAA', 'AABCCCCCBAA', 'AABCAAACBAA', 'AABCADACBAA', 'AABCAAACBAA', 'AABCCCCCBAA', 'AABBBBBBBAA', 'AAAAAAAAAAA'])).toEqual(5);
        expect(countLayers(['AAAAAAAAAAA', 'AABBBBBBBAA', 'AABCCCCCBAA', 'AABCAAACBAA', 'AABCABACBAA', 'AABCAAACBAA', 'AABCCCCCBAA', 'AABBBBBBBAA', 'AAAAAAAAAAA'])).toEqual(5);
        expect(countLayers(['AAAAAAAAAAA', 'AABBBBBBBAA', 'AABCCCCCBAA', 'AABCDDDCBAA', 'AABCDDDCBAA', 'AABCDDDCBAA', 'AABCCCCCBAA', 'AABBBBBBBAA', 'AAAAAAAAAAA'])).toEqual(4);
        expect(countLayers(['FFFFFFFFFFFFFFFFFFFFFFFFF', 'FFFFFFFFFFFFFFFFFFFFFFFFF', 'FFFFGGGGGGGGGGGGGGGGGFFFF', 'FFFFGGGAAAAAAAAAAAGGGFFFF', 'FFFFGGGAABBBBBBBAAGGGFFFF', 'FFFFGGGAABCCCCCBAAGGGFFFF', 'FFFFGGGAABCDDDCBAAGGGFFFF', 'FFFFGGGAABCDDDCBAAGGGFFFF', 'FFFFGGGAABCDDDCBAAGGGFFFF', 'FFFFGGGAABCCCCCBAAGGGFFFF', 'FFFFGGGAABBBBBBBAAGGGFFFF', 'FFFFGGGAAAAAAAAAAAGGGFFFF', 'FFFFGGGGGGGGGGGGGGGGGFFFF', 'FFFFFFFFFFFFFFFFFFFFFFFFF', 'FFFFFFFFFFFFFFFFFFFFFFFFF'])).toEqual(6);
    });
});
